#!/usr/bin/env bash
# This script displays the PID and process name of processes whose name contains the word 'bash'
for pid in /proc/[0-9]*/; do
    if [ -e "${pid}comm" ]; then
        process_name=$(<"${pid}comm")
        if [[ "$process_name" == *bash* ]]; then
            echo "$(basename "$pid") $process_name"
        fi
    fi
done
