#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process
# Get the PID of the 4-to_infinity_and_beyond script
pid=$(pgrep -f "4-to_infinity_and_beyond")
# If the PID is found, kill the process
if [ -n "$pid" ]; then
    kill "$pid"
fi
