#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall
# Get the PID of the 4-to_infinity_and_beyond script
pid=$(pgrep -f "4-to_infinity_and_beyond")
# If the PID is found, terminate the process using pkill
if [ -n "$pid" ]; then
    pkill -f "4-to_infinity_and_beyond"
fi
