#!/bin/bash

# Find the process ID (PID) of the 7-highlander script and kill it
PID=$(pgrep -f 7-highlander)

if [ -n "$PID" ]; then
  kill -SIGTERM "$PID"
else
  echo "7-highlander process not found"
fi
