#!/usr/bin/env bash
# This script stops the 7-highlander process when run
# Check if the 7-highlander process is running
if pgrep -f "7-highlander" >/dev/null; then
    # Get the PID of the 7-highlander script
    pid=$(pgrep -f "7-highlander")
    
    # If the PID is found, terminate the process using pkill
    pkill -TERM -P "$pid"
    echo "OK"
else
    echo "7-highlander not running"
fi
