#!/usr/bin/env bash
# This script finds and kills the 7-highlander process

# Find the process ID (PID) of the 7-highlander script
PID=$(pgrep -f 7-highlander)

if [ -n "$PID" ]; then
  kill -9 "$PID"
  echo "7-highlander process has been killed"
else
  echo "7-highlander process not found"
fi
